# Generated by Django 4.1.3 on 2022-12-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_postal', models.CharField(max_length=7, verbose_name='Codigo Postal')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='trabajo.provincia')),
            ],
        ),
    ]
