# Generated by Django 4.1.3 on 2022-12-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0002_alter_provincia_options_alter_provincia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre_ciudad'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
    ]
